// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTncJEssLge_yxW91ITd4mERB_G1W7IzY',
    appId: '1:54272111128:web:d2745c348712e2266dc96d',
    messagingSenderId: '54272111128',
    projectId: 'event-planning-flutter',
    authDomain: 'event-planning-flutter.firebaseapp.com',
    storageBucket: 'event-planning-flutter.firebasestorage.app',
    measurementId: 'G-M416DVKT1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuaPcRgN12_N88BUpzTBs6y-XBvti-ev4',
    appId: '1:54272111128:android:5b823a531fd605a36dc96d',
    messagingSenderId: '54272111128',
    projectId: 'event-planning-flutter',
    storageBucket: 'event-planning-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd69b84Nt1sbn3gqS5R147HN9seYQ4Qzs',
    appId: '1:54272111128:ios:ba21b74092b7d64f6dc96d',
    messagingSenderId: '54272111128',
    projectId: 'event-planning-flutter',
    storageBucket: 'event-planning-flutter.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd69b84Nt1sbn3gqS5R147HN9seYQ4Qzs',
    appId: '1:54272111128:ios:ba21b74092b7d64f6dc96d',
    messagingSenderId: '54272111128',
    projectId: 'event-planning-flutter',
    storageBucket: 'event-planning-flutter.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTncJEssLge_yxW91ITd4mERB_G1W7IzY',
    appId: '1:54272111128:web:d7582c12f09507d56dc96d',
    messagingSenderId: '54272111128',
    projectId: 'event-planning-flutter',
    authDomain: 'event-planning-flutter.firebaseapp.com',
    storageBucket: 'event-planning-flutter.firebasestorage.app',
    measurementId: 'G-6NK9CQDFBT',
  );
}
